<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Creature extends Model
{

    protected $fillable = [
        'user_id',
        'name',
        'max_hp',
        'current_hp',
        'hit_dice',
        'ac',
        'ac_source',
        'initiative',
        'speed',
        'strength',
        'strength_mod',
        'strength_save',
        'strength_save_proficiency',
        'athletics',
        'athletics_proficiency',
        'athletics_expertise',
        'dexterity',
        'dexterity_mod',
        'dexterity_save',
        'dexterity_save_proficiency',
        'acrobatics',
        'acrobatics_proficiency',
        'acrobatics_expertise',
        'sleight_of_hand',
        'sleight_of_hand_proficiency',
        'sleight_of_hand_expertise',
        'stealth',
        'stealth_proficiency',
        'stealth_expertise',
        'constitution',
        'constitution_mod',
        'constitution_save',
        'constitution_save_proficiency',
        'intelligence',
        'intelligence_mod',
        'intelligence_save',
        'intelligence_save_proficiency',
        'arcana',
        'arcana_proficiency',
        'arcana_expertise',
        'history',
        'history_proficiency',
        'history_expertise',
        'investigation',
        'investigation_proficiency',
        'investigation_expertise',
        'nature',
        'nature_proficiency',
        'nature_expertise',
        'religion',
        'religion_proficiency',
        'religion_expertise',
        'wisdom',
        'wisdom_mod',
        'wisdom_save',
        'wisdom_save_proficiency',
        'animal_handling',
        'animal_handling_proficiency',
        'animal_handling_expertise',
        'insight',
        'insight_proficiency',
        'insight_expertise',
        'medicine',
        'medicine_proficiency',
        'medicine_expertise',
        'perception',
        'perception_proficiency',
        'perception_expertise',
        'survival',
        'survival_proficiency',
        'survival_expertise',
        'charisma',
        'charisma_mod',
        'charisma_save',
        'charisma_save_proficiency',
        'deception',
        'deception_proficiency',
        'deception_expertise',
        'intimidation',
        'intimidation_proficiency',
        'intimidation_expertise',
        'performance',
        'performance_proficiency',
        'performance_expertise',
        'persuasion',
        'persuasion_proficiency',
        'persuasion_expertise',
        'actions',
        'modifiers',
        'spells',
        'resources',
        'show_notepad',
        'show_resources',
        'show_spells',
        'notes',
        'skills_auto_filled',
    ];

    protected $casts = [
        'actions' => 'array',
        'modifiers' => 'array',
        'spells' => 'array',
        'resources' => 'array',
        'special_skill_modifiers' => 'array',
        'hit_dice' => 'array',
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }
}
